apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --listen-client-urls=http://127.0.0.1:2379,http://${NODE_IP}:2379
    - --advertise-client-urls=http://${NODE_IP}:2379
    - --data-dir=/var/lib/etcd
    - --name=${NODE_NAME}
    - --listen-peer-urls=http://${NODE_IP}:2380
    - --initial-cluster-state=new
    - --initial-cluster=${NODE_NAME}=http://${NODE_IP}:2380,${OTHER_NODE_NAME}=http://${OTHER_NODE_IP}:2380
    - --initial-advertise-peer-urls=http://${NODE_IP}:2380
    image: gcr.io/google_containers/etcd-amd64:3.1.11
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd
