apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --listen-client-urls=http://127.0.0.1:2379,https://${NODE_IP}:2379
    - --advertise-client-urls=https://${NODE_IP}:2379
    - --data-dir=/var/lib/etcd
    - --name=${NODE_NAME}
    - --listen-peer-urls=https://${NODE_IP}:2380
    - --initial-cluster-state=new
    - --initial-cluster=${NODE_NAME}=https://${NODE_IP}:2380,${OTHER_NODE_NAME}=https://${OTHER_NODE_IP}:2380
    - --initial-advertise-peer-urls=https://${NODE_IP}:2380
    - --cert-file=/certs/server.pem
    - --key-file=/certs/server-key.pem
    - --client-cert-auth
    - --trusted-ca-file=/certs/ca.pem
    - --peer-cert-file=/certs/peer.pem
    - --peer-key-file=/certs/peer-key.pem
    - --peer-client-cert-auth
    - --peer-trusted-ca-file=/certs/ca.pem
    image: gcr.io/google_containers/etcd-amd64:3.1.11
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd
    - mountPath: /certs
      name: certs
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd
  - hostPath:
      path: /srv/kubernetes/pki/etcd
    name: certs
